# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfaffc8a1452a50f970a8346a472b77d4a739e0f4272aea88e4c8f602b363e2550c5cb0fa7b733791e078d5725dfd82fca9a9d3a9d2bcb38b0fd324e8ed23a95

test:
  secret_key_base: f75bb1f0ea9dfcc53169bb0af1ffd68aee07a71fdf4ea8b5492abcc3908a7b0c57875da1026dd45b3497cba8625ca038ce0a89b98dbae9860d6b90546416ca55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
